//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_ASP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hang
    {
        public string HangID { get; set; }
        [Display(Name = "Tên hàng")]
        public string HangName { get; set; }
        public string SKU { get; set; }
        public string HangImage { get; set; }
        public string MoTa { get; set; }
        public string Note { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public string LoaiHangID { get; set; }
        public string ThuongHieuID { get; set; }
        public string NhaCungCapID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual LoaiHang LoaiHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
