//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_ASP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        public int KhachHangID { get; set; }
        [Required(ErrorMessage ="{0} Không được để trống!")]
        public string KhachHangName { get; set; }
        [Required(ErrorMessage = "{0} Không được để trống!")]
      
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required(ErrorMessage = "{0} Không được để trống!")]
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "{0} Không được để trống!")]
        public string MatKhau { get; set; }
    }
}
